name: Generate Task

on:
  issues:
    types: [opened]

jobs:
  Generate-Task:
    runs-on: ubuntu-latest
    if: ${{ github.event.issue.title == 'Generate Task' }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Install python packages
      run: |
        python -m pip install --upgrade pip
        pip install openai

    - name: Generate task
      id: generate_task
      run: |
        python scripts/generate_task.py ${{ secrets.OPENAI_API_KEY }} "${{ github.event.issue.body }}" '{"difficulty": "medium", "language": "Java"}'
      
    - name: Update issue with task
      uses: actions/github-script@v6
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const fs = require('fs');
          const taskContent = fs.readFileSync('tasks/new_task.md', 'utf8');
          github.rest.issues.update({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: taskContent,
          });
